development: &non_production_settings
  site_url: http://localhost:3000
  site_name: PeopleTantra
  admin_email: bort@bort.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://closed.peopletantra.com
  site_name: PeopleTantra 
  admin_email: rails@socialsync.org
  
production:
  site_url: http://www.peopletantra.com
  site_name: PeopleTantra
  admin_email: rails@socialsync.org